I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00keymap.rpy", line 421, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 421, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 421, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 440, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
AttributeError: 'NoneType' object has no attribute 'stores'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/cero/renpy-7.3.5-sdk/renpy/bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "/home/cero/renpy-7.3.5-sdk/renpy/main.py", line 480, in main
    if renpy.parser.report_parse_errors():
  File "/home/cero/renpy-7.3.5-sdk/renpy/parser.py", line 2929, in report_parse_errors
    renpy.display.error.report_parse_errors(full_text, error_fn)
  File "/home/cero/renpy-7.3.5-sdk/renpy/display/error.py", line 187, in report_parse_errors
    error_fn=error_fn,
  File "/home/cero/renpy-7.3.5-sdk/renpy/game.py", line 281, in invoke_in_new_context
    return callable(*args, **kwargs)
  File "/home/cero/renpy-7.3.5-sdk/renpy/display/error.py", line 45, in call_exception_screen
    return renpy.ui.interact(mouse="screen", type="screen", suppress_overlay=True, suppress_underlay=True)
  File "/home/cero/renpy-7.3.5-sdk/renpy/ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/cero/renpy-7.3.5-sdk/renpy/display/core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/home/cero/renpy-7.3.5-sdk/renpy/display/core.py", line 3166, in interact_core
    renpy.exports.reload_script()
  File "/home/cero/renpy-7.3.5-sdk/renpy/exports.py", line 1771, in reload_script
    renpy.game.call_in_new_context("_save_reload_game")
  File "/home/cero/renpy-7.3.5-sdk/renpy/game.py", line 332, in call_in_new_context
    return renpy.execution.run_context(False)
  File "/home/cero/renpy-7.3.5-sdk/renpy/execution.py", line 908, in run_context
    context.run()
  File "renpy/common/00keymap.rpy", line 421, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 421, in script
    python hide:
  File "/home/cero/renpy-7.3.5-sdk/renpy/ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/cero/renpy-7.3.5-sdk/renpy/python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00keymap.rpy", line 421, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 440, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "/home/cero/renpy-7.3.5-sdk/renpy/loadsave.py", line 398, in save
    roots = renpy.game.log.freeze(None)
  File "/home/cero/renpy-7.3.5-sdk/renpy/python.py", line 1925, in freeze
    self.complete(False)
  File "/home/cero/renpy-7.3.5-sdk/renpy/python.py", line 1531, in complete
    self.current.stores[name], self.current.delta_ebc[name] = sd.get_changes(begin)
AttributeError: 'NoneType' object has no attribute 'stores'

Linux-4.13.0-32-generic-x86_64-with-debian-stretch-sid
Ren'Py 7.3.5.606
 
Thu Jul  2 17:31:36 2020
